#!/bin/sh -e

SUPPORTED_FLAVOURS='amd64 arm64 armmp powerpc64 s390x generic'
ROOTDISK_QEMU_IF=virtio
ROOTDISK_LINUX_NAME=nonexistent
. debian/tests/test-common

cat >>"${CONFDIR}/initramfs.conf" <<EOF
MODULES=list
BUSYBOX=n
FSTYPE=ext2
EOF
cat >"${CONFDIR}/modules" <<EOF
ext2
virtio_pci
virtio_blk
EOF
build_initramfs

build_rootfs_ext2

run_qemu_nocheck
grep -qF "ALERT!  /dev/nonexistent does not exist.  Dropping to a shell!" "${OUTPUT}"
grep -qF "(initramfs) " "${OUTPUT}"

run_qemu_nocheck "panic=-1"
grep -qF "Rebooting automatically due to panic= boot argument" "${OUTPUT}"
! grep -qF "(initramfs) " "${OUTPUT}"

# Needs commit 6300aa109a7c8651a5e0c4d84ca10b363ddd5387 from initramfs-tools 0.138
#run_qemu_nocheck "panic=0"
#grep -qF "Halting automatically due to panic= boot argument" "${OUTPUT}"
#! grep -qF "(initramfs) " "${OUTPUT}"
